### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by LaurenceRLewis** [WhatSock/apex#25]
Fix styles for:

- STANDARD CHECKBOXES
- TOGGLE BUTTONS
- ARIA LISTBOX (SORTABLE)
- Menus
- STANDARD RADIOS

Improving visually styles for:
- COMBOBOX

Review use of Test pages heading for the components Parent page. It does not really work.

**Comment by accdc** [comment]
"Review use of Test pages heading for the components Parent page. It does not really work."

I appreciate the enhancements as always, but I'm not sure about this one. How does the heading not work?

Thanks,
Bryan

**Comment by LaurenceRLewis** [comment]
Hi @accdc 

In my opinion this set of pages needs a heading above the instructional content, and below the navigation,  that describes the purpose. Having the main page heading that people encounter as Test pages is potentially confusing. 
Test pages is a heading for the navigation only. _Personally I really don't see a need for this as the navigation is self explanatory due to styling and position._ On the Component pages the Test pages heading is associated with the menu due to its vertical alignment.

On these parent pages my suggestion is to remove the Test pages heading and incorporate a descriptive main page heading that describes the page content.

Noting this is a personal observation and happy to get others feedback :-)

Example page [ARIA Comboboxes](http://www.whatsock.com/Templates/Comboboxes/index.htm)

**Comment by accdc** [comment]
That sounds good to me, though Test Pages will still need to be a heading, even if it is a fake one using role="heading" plus aria-level, because it helps a lot for blind folks like me to quickly locate that particular section. :)

**Comment by accdc** [comment]
I'm going to close this as an issue for now. Please open again if it is still relevant.
