### ISSUE TITLE
Broken components need checking

### ISSUE THREAD

**Issue by LaurenceRLewis** [WhatSock/apex#26]
Broken:
- ARIA LISTBOX (STANDARD)
- ARIA LISTBOX (STRAYLIGHT INTERNAL CONTENT)
- ARIA LISTBOX (STANDARD EXTERNAL)

**Comment by accdc** [comment]
This appears to not be an issue. I checked all the examples and they are working on my end. E.G. After pressing Ctrl+Shift+Delete (in Chrome) and clearing the local cached files, then visiting
http://whatsock.com/Templates/Listboxes/Standard/index.htm
I can interact with the listbox as expected. The same on the downloaded copy of the Git repo as well. I'll close this for now, but if you are still encountering the same problem, please reopen and include steps to reproduce.

**Comment by LaurenceRLewis** [comment]
I’ll clear my cache and retest to confirm.
