### ISSUE TITLE
dayToday class moves to selected day

### ISSUE THREAD

**Issue by adam-delaney** [WhatSock/apex#28]
## Issue
The dayToday class seems to move to the selected day. I would expect that dayToday class would remain on the date for today's Date. I can replicate the issue for this example: http://whatsock.com/Templates/Datepickers/Basic/index.htm.

## Steps to reproduce
1) Launch the datePicker and inspect the class for today's date. This should have the dayToday.
2) Select another date other than today
3) Relaunch the datePicker and dayToday class is not on today's date.

**Comment by accdc** [comment]
Thanks, I just pushed a fix for this issue. The core is the same, but the Datepicker module includes logic to only set the today class and aria-current on the cell matching today's date. To load the new code, you may need to clear your browser file cache to make sure everything loads correctly when testing. I'll close this issue as fixed for now, but please reopen if you notice any other issues relating to this.

**Comment by adam-delaney** [comment]
I've tested this and it works as expected. Thanks @accdc for the quick fix!
