### ISSUE TITLE
Visual selected and focused on radio button group may be confusing

### ISSUE THREAD

**Issue by LaurenceRLewis** [WhatSock/apex#29]
Make sure the radio button is visible rather than having the radio buttons look like buttons.

**Comment by accdc** [comment]
I'm not sure I understand, do you mean the underlying native radio buttons, or the simulated ARIA radio buttons?

**Comment by LaurenceRLewis** [comment]
Hi @accdc (Bryan)

The radio buttons are visually square blocks with test inside making each look like a regular button. Keyboard only users may have the expectation that they can tab to each one. I have change the styling so they look like round radio buttons with the label alongside. The radio button element fills when selected and users know to navigate the group using arrow keys.

**Comment by LaurenceRLewis** [comment]
Closing as fixed. If you have any other questions please let me know :-)
