### ISSUE TITLE
publish this package to npm

### ISSUE THREAD

**Issue by Anubarak** [WhatSock/apex#39]
We would like to use this package but it seems there is no npm package for it.
Using it in our module bundler without will cause several TS/include issues so all we can do is to turn off all errors/warnings and lose many functions we usually like.

Is there are chance you could publish it properly so it's ready to use in all environments without manually downloading files? 
Thank you very much

**Comment by accdc** [comment]
Hi, I hadn't thought of that before. Yes of course, let me look into it and see what the process is for doing this.

**Comment by accdc** [comment]
Hi, this should now be fixed. :) 
https://github.com/WhatSock/apex/commit/728dabca9938a8d41ce4099e19041e00e361e320
