### ISSUE TITLE
mobile input focus error

### ISSUE THREAD

**Issue by impetoyt** [WhatSock/apex#40]
I was checking the datepicker work at:
https://whatsock.com/Templates/Datepickers/Basic/index.htm
On desktop it works but if you try on a smarthphone there is an issue about the focus input. I tried on chrome desktop using the virtual mobile console and also with a real smartphone.

Here the step to get the error in both case:
1) click on the button picker. The picker will open;
2) choose a date from the picker. Focus will move on the input field;
3) click outside the input field (any place but not on the button picker);
4) click on the button picker, the picker will open. Don't choose a date but click outside (any place but not on the button picker). The picker automatic close;
5) click on the input field and you will see that the focus will not move on the input field and you can't digit. In the console appear an error related to the set focus method.

[https://i.ibb.co/vZjCKdh/datepicker.png](https://i.ibb.co/vZjCKdh/datepicker.png)

**Comment by accdc** [comment]
Hi, we are unable to reproduce this issue. What is the make and browser of the smart phone you are using? E.G. iPhone12 Pro with Safari, etc.

At times the mobile desktop simulator is not always reliable when it comes to identifying actual mobile device issues.

Thanks,
Bryan

**Comment by impetoyt** [comment]
Above the video with the issue, I used a samsung S22+ with google chrome app. The same issue happens on desktop (virtual mobile feature on latest version of chrome desktop). Let me know if you are still unable to reproduce the issue.

[https://we.tl/t-NV6NhxjlFD](https://we.tl/t-NV6NhxjlFD)

**Comment by accdc** [comment]
Hi, I am totally blind so am having trouble tracking this down. 

Can you do me a favor and run the test again on the following test page?
https://whatsock.com/Templates/Datepickers/Basic/test.htm

Then please post the entire error that is generated in the console.

Hopefully this will help zero in on exactly where in the code this issue is occurring.

**Comment by accdc** [comment]
Hi, we were able to reproduce the issue and it has been corrected. You should not have any further errors like this. :)
