### ISSUE TITLE
Datepicker double open

### ISSUE THREAD

**Issue by impetoyt** [WhatSock/apex#41]
inside an html page you just build two different input with two different button which will render two different picker.

the default behaviour is:
1) click on the first button, the picker it will open. Just wait that the animation is completed.
2) click on the second button, the first picker will automatically close and the second picker will open.

here the issue (250ms animation using Velocity it is sufficient):
1) click on the first button, the picker it will open. Don't wait to complete the animation and click on the second button.
2) the first picker will not automatically close and the second picker will open together with the first one.

Using 0ms animation avoid the problem but it's not a good solution.

![image](https://github.com/WhatSock/apex/assets/135225141/48f4d45b-5fd1-495e-b269-1a38fc075888)

**Comment by accdc** [comment]
Hi, I just tested this on my end and the fix does appear to solve the double rendering. Please reopen this if you notice the same behavior after updating your code to use the core Blade Runner 4X.js version plus the updated Datepicker.js module code.
