### ISSUE TITLE
localizer

### ISSUE THREAD

**Issue by carlafranca** [WhatSock/apex#43]
Is there a way to add localization to this plugin? I would lile to have it as a configuration.
also to have different types of displaying the day name as single letter or double letter.

this.dayShort = date.toLocaleString(lang, { weekday: "short" });
this.month = date.toLocaleString(lang, { month: "long" });
this.monthShort = date.toLocaleString(lang, { month: "short" });
 this.monthNumber = Number(date.toLocaleString(lang, { month: "2-digit" }));
 
 By the way, thanks for this accessiblity datepicker.

**Comment by accdc** [comment]
Hi, yes of course. :) When I built it I tried to make sure everything could be customized.

You can change the short and long weekday and even the month assignments by adding the following code to your setup declaration.

```
// Set month names
months: [
'January',
'February',
'March',
'April',
'May',
'June',
'July',
'August',
'September',
'October',
'November',
'December'
],

// Set short and long weekday names
days: [
{
s: 'S',
l: 'Sunday'
},
{
s: 'M',
l: 'Monday'
},
{
s: 'T',
l: 'Tuesday'
},
{
s: 'W',
l: 'Wednesday'
},
{
s: 'T',
l: 'Thursday'
},
{
s: 'F',
l: 'Friday'
},
{
s: 'S',
l: 'Saturday'
}
],
```

This is directly copied from the setup config options within the help file in the download by opening:
`Help/Module Imports/Dynamic Components/Datepicker.txt`

There you can see all of the other configuration options you can use to customize the format, layout, and functionality of the datepicker however you wish.

Does this answer your question?

**Comment by carlafranca** [comment]
Yes, thank you
