### ISSUE TITLE
Feature view for month/years selection

### ISSUE THREAD

**Issue by carlafranca** [WhatSock/apex#44]
Hi,This is not an issue but more a new feature.
Is ts possible to extend the plugin to add a new view for mont/years?
I would like to be ble to click on month/Year and show a list of month/years for selection.
Here is an exmaple.
https://designsystem.digital.gov/components/date-picker/

Thanks

**Comment by accdc** [comment]
Hi, at present this is not possible using the current design. It's a good idea though. I'll add this to my feature list to implement in a future update of the datepicker module.

**Comment by impetoyt** [comment]
As carlafranca I think it would be a big improvment have the possiblity to choose directly the month and the year.

**Comment by accdc** [comment]
Thanks, I understand. I'll look into that. :)

**Comment by carlafranca** [comment]
@impetoyt , that's exactly the reason I was looking for this enhancement.
I tried to play a bit with the code but couldn't fully implement it.

**Comment by accdc** [comment]
Hi, I have added this feature to the Datepicker module. You can try it out here.
https://whatsock.com/Templates/Datepickers/Basic/index.htm

The following options have been added to the config:

```
// Optionally convert the static year field into a year selector dropdown.
yearSelect: true,
yearSelectMin: 1900,
yearSelectMax: 2030,
// Optionally convert the static month field into a month selector dropdown.
monthSelect: true,
```

This is already in the Git repo so you can download it there. Simply change the styling as you wish.

**Comment by carlafranca** [comment]
Just a quick check, Do we have the accessibility for that too?
Thank you so much for this feature.

**Comment by accdc** [comment]
Yes of course, I tested it using JAWS and NVDA in Edge, Chrome, and Firefox. It is fully keyboard and screen reader accessible. I also tested it on iOS with Voiceover to verify full mobile device accessibility as well. As a blind user myself, I made sure it was fully accessible before releasing it. :)

**Comment by carlafranca** [comment]
OMG @accdc you are fantastic. Thank you so much for that.

**Comment by accdc** [comment]
No problem, glad to help. :) Please let me know if you need anything else added or fixed in the future.

**Comment by impetoyt** [comment]
In case you are using a disabled range date by default the years and moths selection are disabled in according with the range date provided. Istead if you are using the select field the user can change the month and go to a month that in truth is disabled. You could be add to the code the same feature of the years selection:
```
		yearSelectMin
		yearSelectMax
```

something like:
```
		monthSelectMin
		monthSelectMax
```

in this way in the select will appear selectable only for example june and july and the other months are disabled. Or another solution maybe more powerful is to provide a list of the months that should appear in the select field: February, June, September. So the code will be something like (February = 2, June = 6, September = 9):
```
		monthSelect: [2, 6, 9]
```

**Comment by accdc** [comment]
Hi, I just pushed an update that will automatically filter the available years and months based on the disabled state of the calendar dates. This doesn't need to be configured but will happen automatically when you set a disabled date range or choose to block off specific months or years.
