### ISSUE TITLE
DateFormats with '-' separator instead of '/'

### ISSUE THREAD

**Issue by GuptSmita** [WhatSock/apex#52]
hello, I am trying to specify different format like "dd-mm-yyyy" but it seems not working. 
I think its breaking on 'OnActivate"  on this line  dc.target.value = dc.formatDate(dc);
Can you please help?
Thanks a lot

**Comment by accdc** [comment]
Hi, if you still need help with this just let me know. :)

**Comment by GuptSmita** [comment]
Thanks for quick response. Much apprciated. I have two questions though-
Do you have any documentation for datepicker's additional methods ? 
Also, Do you have any example where you have used date format as "DD-MM-YYYY"?

**Comment by accdc** [comment]
Hi, no problem, you can see a list of available methods at:
https://whatsock.com/Templates/Datepickers/index.htm
Scroll down to the section "Programmatic control".

This is also available in the download within the file: `Help/Module Imports/Dynamic Components/Datepicker.txt`

I don't have any live examples of the alternative date format, but you can easily specify this within the setup config by setting the desired date format like so:

```
// Using a token system, set a specific date string format to be used when setting the selected value into the calendar input box
// 'YYYY': 4 digit year, 2019
// 'MMMM': Full name of month, January, etc.
// 'dddd': Full name of weekday, Monday, etc.
// 'MM': 2 digit month, 01, etc.
// 'DD': 2 digit day, 01, etc.
// 'Do': getDateOrdinalSuffix, 1st, 2nd, 3rd.
// 'M': 1 or 2 digit month, 1 through 12
// 'D': 1 or 2 digit day, 1 through 31.

inputDateFormat: 'MM/DD/YYYY',
```

**Comment by accdc** [comment]
Simply change the / symbols within the date string to '-' to change the output.
