### ISSUE TITLE
Does datepicker supports partial date formats?

### ISSUE THREAD

**Issue by GuptSmita** [WhatSock/apex#54]
Hello Bryan and team,
I am wondering if this accessible datepicker supports partial date formats like "MM/YYYY". I tried to provide this date format as input but it didn't work. Can you please provide more information/example if its being supported. Thank you!

**Comment by accdc** [comment]
Hi, it does not at present. When the datepicker opens, it has to have a day selected to initiate with a specific date, including day, month, and year. It's possible I can add this though. What do you expect to happen if only the month and year are specified?

**Comment by GuptSmita** [comment]
Hello, thanks for the reply. Yes we are using this datepicker and wondering if we can have this partial date option for the end users so that they can enter only month and year for some specific date fields like month of joining, travel duration etc (where exact date is not required). Possible formats would be "mm/yyyy", "mm/yy", "yyyy/mm" or "yy/mm".
Let me know please if you need more information,
Thanks a lot

**Comment by accdc** [comment]
Thanks for explaining. When the calendar opens with a specified month and year, day 1 will automatically be selected for that month. All other dates will also be displayed as normal. Is that what you expect to see when the calendar opens like this?

**Comment by GuptSmita** [comment]
![image](https://github.com/WhatSock/apex/assets/146905597/72b9eb48-6d89-4fac-bf7c-f088e1f85075)
I am looking for something like this. so that there will be no date option, just month and year. By default, when calendar opens, it can show the current year and month with no date table. I just want to have short dates with above mentioned formats. Let me know please if more information is needed. Thank you

**Comment by accdc** [comment]
Thanks, I am totally blind however, so I'll need you to describe exactly what it is that the attached image shows.

**Comment by GuptSmita** [comment]
Hello, 
Sure, I will describe it here-
When a datepicker opens, it should only have two dropdowns, one for month and one for year. It should not contain any week or date cells. So for example- lets refer to this accessible datepicker, for partial/short dates, it should only have rows which has "yearSelector" and "monthSelector" classes. It should not have "week" and "day" classes.
Please let me know if needs more information, Thanks a lot

**Comment by accdc** [comment]
Thanks, that helps a lot. :) 

I will work on getting this added, though I can't say how soon this will be. I'll send word when I know more.

All the best,
Bryan

**Comment by GuptSmita** [comment]
Thanks to you too, please feel free to let me know if you have any further question, and also Keep me posted once you know its expected delivery date, so that we can manage our things accordingly.
Really appreciated it 🙏

**Comment by accdc** [comment]
No problem, I plan to have it done within the next couple of weeks. If I can find some extra time between projects then it will be sooner. I'll keep you posted.

**Comment by accdc** [comment]
Hi, I have pushed an update that I believe corrects the issue.

There is a new feature that you can enable by setting the property `monthOnly` to true within your datepicker config.

```
// Specify that only the year and month selector will be rendered, and no individual dates.
// Set inputDateFormat to return the correct string value when the datepicker closes. For example:
// inputDateFormat: 'MM/YYYY',
monthOnly: true,
```

Additionally you can enter any month/year or year/month date string into the input field and the datepicker will attempt to resolve the date.

Examples: `7/24` , `24/11` , `11/1979`

I'll close the issue as fixed, but please test it and let me know if that is what you were looking for.

**Comment by GuptSmita** [comment]
great, thanks a lot, really appreciate it. I will pull new changes shortly, and let you know.
Thanks again 🙏

**Comment by accdc** [comment]
FYI, I realized I forgot to add the date format string code that will return a 2 digit year, so I added that last night. This is a new token within the date format options: "yy", which will be populated by the 2 digit year.

You can set this using the inputDateFormat property like so.

```
inputDateFormat: 'MM/yy',
```

Or in whatever combination you wish.

All the best,
Bryan

**Comment by GuptSmita** [comment]
Hello Bryan,
I have started working on using short dates in datepicker, but i am having these issues-
1- line 389 - yy: ("0" + dc.range.current.year).slice(-2) in datepicker.js is breaking for short dates as well as regular/full dates(dd-mm-yyyy)
2- Also, month dropdown is working fine with keyboard, but not with mouse. As soon as month dropdown opens using mouse click, it close the whole datepicker, 
so user is not able to select month using mouse.

When its possible for you, can you please confirm me if you are having same issues.
Also, have you included this option/example in your documentation?

Thanks a lot,
Smita

**Comment by accdc** [comment]
Hi, I've been away for a while so am just looking into this. Which example in the Templates folder best shows this behavior?

**Comment by accdc** [comment]
Hi, I apologize for the delay, I've been out due to health issues. I hope to be able to work on fixing this in the near future though. I'm going to reopen this issue so I have it at the top of my list.

**Comment by accdc** [comment]
In looking into this further, it looks like introducing the new functionality broke some needed functionality, so I restored the prior datepicker.js version temporarily.

I'll work on fixing these issues using a fresh start so it doesn't compound the problems.

**Comment by GuptSmita** [comment]
Hello Bryan,
Thank you so much in looking into this.

**Comment by accdc** [comment]
Hi, I just pushed an update that I hope will address your prior needs and hopefully fix the additional bugs you mentioned.

There is a new Datepicker template that you can use to play with, which is also live at: https://whatsock.com/Templates/Datepickers/Basic%20Short/index.htm

You can see how it works within the repo download.

Please let me know if this is what you had in mind.

**Comment by GuptSmita** [comment]
Hello Bryan,
Thanks for the updates and understanding my issues so well. Yes, this is same what I had in my mind.

Just one question, While playing with the template only, I noticed that i am not able to open "Month" datepicker from "Enter" key. As soon as I am pressing enter key, its closing the datepicker and selecting the month. Its opening on only Space keypress.
However, the year dropdown is working prperly by opening on "enter" and "Space" key.

Do you think this behaviour is possible to be on month dropdown as well? So that it will open on first "Enter" keypress and select the month/close the datepicker on second "Enter" keypress.

Let me know please,
Thanks a lot

**Comment by accdc** [comment]
Hi, unfortunately there isn't without having to change the UI by adding another button to the datepicker for saving the selected month, and that will take longer because I would have to redesign the table renderring layout within the script and that would impact all datepickers across the board.

As a compromise, I set the month to save on Enter instead of the year since it is more likely that somebody making a selection will want to save on a granular month selection rather than on a global year selection.

From an accessibility perspective, a native select element such as this is a common control type that non-sighted screen reader users have been using for many years and you can also press Alt+DownArrow (on Windows) to pop open the available months as well as the Spacebar.

If it's confusing to first set focus on the Month select instead of the Year select when it opens, I can change that fairly quickly if you wish to make the flow a bit more intuitive.

Otherwise, I'm not sure when I will have the time to redesign the table layout to add another control within it.

**Comment by accdc** [comment]
Hi, as an FYI, I did push an update late last week that changes the Year and Month selector to work in the same fashion from the keyboard to maintain consistency , plus focus will move to the Year field by default.

It's important to change the helpText property in the setup script to reflect the new instructions for use, which you can test in the live example. When you press F1 it will announce the keyboard instructions while using a screen reader.

**Comment by GuptSmita** [comment]
Thanks a lot Bryan. Really appreciate it.
Yes, I noticed this behavior yesterday when demonstrating this to my team.
Everything looks good now. I am going to pull new changes soon.

Best Regards,

**Comment by GuptSmita** [comment]
hello Bryan,
Hope you are doing well.
I just wanted to inform you that i am facing two mouse issues in short dates-
1- As soon as month dropdown is opened using mouse, its not allowing user to select any other option and closing the whole datepicker
2- when the page is refreshed, the selected date in date field is not reflecting in the datepicker, its setting the dropdown selections to current month and current year.
However, its working very well using keyboard. 
Thanks for all your support,

Regrads,
Smita

**Comment by accdc** [comment]
Hi, I believe I have fixed this, can you please retest? https://whatsock.com/Templates/Datepickers/Basic%20Short/index.htm

**Comment by GuptSmita** [comment]
Hello,

Thanks for the quick response. yes it fixed the month dropdown opening issue with mouse. But it still has these two issues-
1- when selecting the same month with mouse, its not closing the datepicker/finalizing the selection. For example, if I just want to change the year using mouse, even if I am selecting the same momnth, its not triggering action to close the datepicker and finalize the date.
2- On page refreshing, the datepicker is not reflecting what is selected month/year. Its always resetting it to current month/year.

Let me know please if you need more information,
Thanks again

**Comment by accdc** [comment]
I understand better thanks.

I'll work adding a way to save and close the calendar so you can choose the current month.

About the page refresh issue though, every time you refresh the page you reload the javascript that controls the datepicker so all in memory is gone.

What is the scenario that you are trying to accomplish with the page refresh?

**Comment by GuptSmita** [comment]
Its happening well in full dates where when a date is selected, its reflected in the datepicker even on page refresh. For exmaple, for the first time,when i open the full date datepicker(mm-dd-yyyy), its todays date by default, and when I choose "02-30-2010" it stays there and datepicker reflects this date whenever opened even after page refresh.

But this partiular part of holding the selected date(mm-yyyy) is missing in short datepicker. So for the firts time i opening the date picker with empty input field, its on july,2024(current behavior), but when i select 11-2010 and refreshing the page, the opened datepicker show july,2024 and not november,2010.

**Comment by accdc** [comment]
Thanks, I just pushed an update that should correct the problem about saving the current date. You can now simply click the X close icon and it will do so.
E.G. https://whatsock.com/Templates/Datepickers/Basic%20Short/index.htm

Your issue about the page refresh is something I have no control over however.

Browser form field caching is a feature in modern web browsers that preserves the values entered into form fields. This functionality aims to enhance user experience by allowing users to navigate back to forms without losing their entered data. When a user refreshes a webpage, the browser may restore the cached values of form fields. This can occur even when there is no explicit JavaScript or server-side code responsible for repopulating the form fields.

This caching behavior can sometimes be noticed in specific scenarios, such as when entering a full date like '11/25/1979', but not with a partial date like '11/24'. The reason behind this inconsistency lies in how browsers determine the context and format of the input data. Full dates often match the expected format for datepicker fields, making browsers more likely to cache them. Partial dates or other inputs that do not conform to a recognized pattern might be ignored by the caching mechanism.

Since this is stored locally on your computer, clearing the cache removes the stored form data, so the field will appear blank if you refresh the page afterwards.

**Comment by GuptSmita** [comment]
Hello Bryan,
1- I looked at the current solution, and it looks like left/right arrows keys on year dropdown are breaking its functionality when clicking arrow many times its going outside the range and not going back to its initial starting year. Also, I am able to replicate the same behavior on BASIC datepicker as well. Month dropdown and its left/right arrows are working fine.

2- Button is working good, keeping the selection but its behavior is looking inconsistent as on month change, datepicker is closing, making the selection but in year change, this button needs to be pressed. Is it possible to have all selection and datepicker closing on button only and not on month dropdown change.

3- For the datepicker reflecting date selected, thank you for cache explanation but it does not look like cache issue. As if a date is already there in input field in a form on page load, when the datepicker opens it should reflect that date. But that’s okay, may be I will need to look into this more. 

Thanks a lot for all your help,
Smita

**Comment by accdc** [comment]
Thanks, I fixed both 1 and 2. You can test this here. https://whatsock.com/Templates/Datepickers/Basic%20Short/index.htm

Regarding 3, if you have a date already in the input on page load, you can manually set the datepicker to reference the input and parse the date as the initial date for the datepicker setup.

All the best,
Bryan

**Comment by GuptSmita** [comment]
Thanks a lot for all the quick fixes and suggestions.
I am closing this issue.

Regards, 
Smita
