### ISSUE TITLE
How does one use this library in a Django website?

### ISSUE THREAD

**Issue by coredumperror** [WhatSock/apex#56]
The demos look amazing, but I am having a devil of a time figuring out how to incorporate this code into my existing Django-based website. Specifically, I'm baffled as to how to get the dynamic module imports to work, and how I'm supposed to get the right CSS styles added. 

Since I couldn't get dynamic imports to work, I tried the "Standard Script Tags" approach from the README, which seems to have worked to get the Datepicker to behave right. But because there's no CSS, it doesn't _look_ right. I haven't seen any docs on how to deal with that, though.

Any help would be appreciated.

**Comment by accdc** [comment]
- Hi, using the standard JS script tags work best for this type of platform as you discovered.

I'm not familiar with Django, but you should be able to add CSS styles directly within the global CSS editor if it's not possible to directly link to external stylesheets.

So all you need do is copy and paste the CSS styles from the template you like the look of into your website styles.

E.G. These can be found in the download at:

`Templates/Datepickers/Basic/css/datepicker.css`

Plus you can edit these however you like to change anything to better fit your website layout.

All the best,
Bryan

**Comment by accdc** [comment]
I'm going to close this as fixed for the time, but please reopen if you still are having issues.
