### ISSUE TITLE
Error checking window.device in Slider.js

### ISSUE THREAD

**Issue by lukos** [WhatSock/apex#62]
`Slider.js` has code which queries window.device.type, which is undefined on my desktop Chrome so it errors in the console. I'm not sure whether this breaks anything other than the code inside the if statement but presumably easy enough to check `typeof(window.device) !== "undefined"` before checking for the device type?

Again, happy to do a PR if you are happy with the proposed change.

**Comment by lukos** [comment]
Actually, I do think it breaks my loop which fails as soon as the first slider is setup, meaning the remaining sliders are not wired up at all!

**Comment by lukos** [comment]
Is this something that could be added to the online docs? Again, happy to make a PR.

**Comment by lukos** [comment]
Hi Bryan,
yes, that's where I was thinking of putting it, just a section that says, "Slider depends on....". I think this is helpful as well since i noticed there were a number of drag JS files in the distribution so it wouldn't otherwise be obvious which ones to use (unless I looked into the JS file like you suggested!).

**Comment by accdc** [comment]
No problem, I'll add a section for all the widgets and hopefully have this done by the end of this week. :)

**Comment by accdc** [comment]
Closing this issue as completed.
