### ISSUE TITLE
Date selection doesn’t trigger input events

### ISSUE THREAD

**Issue by MatzeKitt** [WhatSock/apex#64]
First of all: thank you for one of the only accessible date pickers. ❤️

During implementation, I noticed that by selecting a date from the date picker, there is no event triggered on the input field field, e.g. the `input` event or the `change` event. Thus, I would love to see the date picker extended to support this by default.

I currently use this workaround to trigger a custom event manually:

```js
const desc = Object.getOwnPropertyDescriptor( HTMLInputElement.prototype, 'value' );
Object.defineProperty( input, 'value', {
	get: desc.get,
	set: function( v ) {
		desc.set.call( this, v );
		input.dispatchEvent( new CustomEvent( 'input' ) );
	}
} );
```

Where `input` is the input field the date picker is attached to.

Source: https://stackoverflow.com/a/72223895/3461955

**Comment by accdc** [comment]
Thanks, I'm glad you find it useful!

I already updated the Datepicker module to include this so it should work now. It uses the internal event tracker, so you will need to first assign the event using the `$A.on()` method as documented in `Help/$A API/DOM Events/On.txt`

E.G.

```
$A.on(inputElement, "input", function(event) {
  // Do something
});
```

Please let me know if this works for you. This should work for both the input and change events.

**Comment by MatzeKitt** [comment]
Thank you, that works, too!
